name: ci

on:
  workflow_dispatch:
  push:
    # branches:
    #   - dev

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    container: debian:11
    steps:
      - name: Install deps
        run: |
          apt-get -yqq update \
            && apt-get -yqq upgrade \
            && apt-get -yqq install --no-install-recommends \
            build-essential \
            ca-certificates \
            curl \
            file \
            g++ \
            gcc \
            gfortran \
            git \
            gnupg2 \
            iproute2 \
            locales \
            make \
            mercurial \
            subversion \
            python3 \
            python3-boto3 \
            unzip \
            zstd \
            && locale-gen en_US.UTF-8 \
            && rm -rf /var/lib/apt/lists/*

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: spack/setup-spack@v2

      - uses: viperML/spack-buildcache-action@main
        with:
          environment: .

      - run: |
          which -a cmake
